package com.my.dao.mesmgr;

import com.my.mode.mesmgr.EtrnlotHis;
import com.my.mode.mesmgr.EtrnlotHisExample;
import com.my.mode.mesmgr.EtrnlotHisKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EtrnlotHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    int countByExample(EtrnlotHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    int deleteByExample(EtrnlotHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    int deleteByPrimaryKey(EtrnlotHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    int insert(EtrnlotHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    int insertSelective(EtrnlotHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    List<EtrnlotHis> selectByExample(EtrnlotHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    EtrnlotHis selectByPrimaryKey(EtrnlotHisKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") EtrnlotHis record, @Param("example") EtrnlotHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    int updateByExample(@Param("record") EtrnlotHis record, @Param("example") EtrnlotHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    int updateByPrimaryKeySelective(EtrnlotHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MESMGR.ETRNLOTHIS
     *
     * @mbggenerated Thu Feb 04 13:59:43 CST 2016
     */
    int updateByPrimaryKey(EtrnlotHis record);
}